// SPDX-FileCopyrightText: 2026 GSI Helmholtz Centre for Heavy Ion Research GmbH <http://www.gsi.de>
// SPDX-License-Identifier: Apache-2.0

// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api/v1` | (string & {});
};

/**
 * The running sdash and the clusters it is configured for.
 */
export type Status = {
    /**
     * The release of sdash, in the form v1.4.0, or "devel" for a build
     * that is not a release.
     *
     */
    version: string;
    /**
     * The git revision the binary was built from. Absent when the
     * build carried no information about it.
     *
     */
    commit?: string;
    /**
     * When the binary was built or its revision was committed. Absent
     * when the build carried no information about it.
     *
     */
    date?: string;
    /**
     * The Go toolchain that built the binary.
     */
    goVersion: string;
    /**
     * The system the binary was built for, as os/arch: linux/amd64,
     * for example.
     *
     */
    platform: string;
    /**
     * Whether sdash was started with --read-only, and so sends nothing
     * that changes a cluster.
     *
     */
    readOnly: boolean;
    /**
     * The clusters sdash is configured for. The list is always
     * present, and empty when there is none.
     *
     */
    clusters: Array<Cluster>;
};

/**
 * A Slurm cluster sdash is configured for.
 */
export type Cluster = {
    /**
     * The name the user gave the cluster in the configuration.
     */
    name: string;
};

/**
 * Why a request was not answered with what it asked for.
 */
export type Error = {
    code: ErrorCode;
    /**
     * The cause in one line, for the person at the browser.
     */
    message: string;
};

/**
 * The cause of an Error, for the program that reads the answer.
 *
 * - `bad_request`: the request is not one the operation accepts.
 * - `not_signed_in`: the request does not carry the session cookie of
 * this run of sdash.
 * - `cross_origin`: the request comes from a page of another origin.
 * - `not_found`: the API has nothing at this address.
 * - `method_not_allowed`: the API has something at this address, but
 * not for this method.
 * - `internal`: sdash failed while answering; its log says why.
 *
 */
export const ErrorCode = {
    BAD_REQUEST: 'bad_request',
    NOT_SIGNED_IN: 'not_signed_in',
    CROSS_ORIGIN: 'cross_origin',
    NOT_FOUND: 'not_found',
    METHOD_NOT_ALLOWED: 'method_not_allowed',
    INTERNAL: 'internal'
} as const;

/**
 * The cause of an Error, for the program that reads the answer.
 *
 * - `bad_request`: the request is not one the operation accepts.
 * - `not_signed_in`: the request does not carry the session cookie of
 * this run of sdash.
 * - `cross_origin`: the request comes from a page of another origin.
 * - `not_found`: the API has nothing at this address.
 * - `method_not_allowed`: the API has something at this address, but
 * not for this method.
 * - `internal`: sdash failed while answering; its log says why.
 *
 */
export type ErrorCode = typeof ErrorCode[keyof typeof ErrorCode];

export type GetStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/status';
};

export type GetStatusErrors = {
    /**
     * The request was not answered with what it asked for. The status says
     * what kind of failure it is, and the body what caused it.
     *
     */
    default: Error;
};

export type GetStatusError = GetStatusErrors[keyof GetStatusErrors];

export type GetStatusResponses = {
    /**
     * The status of the running sdash.
     */
    200: Status;
};

export type GetStatusResponse = GetStatusResponses[keyof GetStatusResponses];
